services:
  - type: web
    name: login-app
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    preDeployCommand: psql "$DATABASE_URL" -f database_postgres.sql
    startCommand: gunicorn app:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: login-app-db
          property: connectionString

databases:
  - name: login-app-db
    plan: free
    databaseName: login_app
